package me.moeyinlo.visualize.jvm.jni

import me.moeyinlo.visualize.jvm.runtime.JvmValue

class JvmSimulatedJniFunctionTable internal constructor(
    val newLocalRef: (JvmJniHandleId?) -> JvmJniHandleId?,
    val deleteLocalRef: (JvmJniHandleId?) -> Unit,
    val newGlobalRef: (JvmJniHandleId?) -> JvmJniHandleId?,
    val deleteGlobalRef: (JvmJniHandleId?) -> Unit,
    val newWeakGlobalRef: (JvmJniHandleId?) -> JvmJniHandleId?,
    val deleteWeakGlobalRef: (JvmJniHandleId?) -> Unit,
    val getObjectRefType: (JvmJniHandleId?) -> JvmJniReferenceType,
    val isSameObject: (JvmJniHandleId?, JvmJniHandleId?) -> Boolean,
    val ensureLocalCapacity: (Int) -> Int,
    val pushLocalFrame: (Int) -> Int,
    val popLocalFrame: (JvmJniHandleId?) -> JvmJniHandleId?,
    val findClass: (String) -> JvmJniHandleId,
    val getObjectClass: (JvmJniHandleId) -> JvmJniHandleId,
    val isInstanceOf: (JvmJniHandleId?, JvmJniHandleId) -> Boolean,
    val getMethodId: (JvmJniHandleId, String, String) -> JvmJniHandleId,
    val getStaticMethodId: (JvmJniHandleId, String, String) -> JvmJniHandleId,
    val getFieldId: (JvmJniHandleId, String, String) -> JvmJniHandleId,
    val getStaticFieldId: (JvmJniHandleId, String, String) -> JvmJniHandleId,
    val getIntField: (JvmJniHandleId, JvmJniHandleId) -> Int,
    val setIntField: (JvmJniHandleId, JvmJniHandleId, Int) -> Unit,
    val getLongField: (JvmJniHandleId, JvmJniHandleId) -> Long,
    val setLongField: (JvmJniHandleId, JvmJniHandleId, Long) -> Unit,
    val getFloatField: (JvmJniHandleId, JvmJniHandleId) -> Float,
    val setFloatField: (JvmJniHandleId, JvmJniHandleId, Float) -> Unit,
    val getDoubleField: (JvmJniHandleId, JvmJniHandleId) -> Double,
    val setDoubleField: (JvmJniHandleId, JvmJniHandleId, Double) -> Unit,
    val getObjectField: (JvmJniHandleId, JvmJniHandleId) -> JvmJniHandleId?,
    val setObjectField: (JvmJniHandleId, JvmJniHandleId, JvmJniHandleId?) -> Unit,
    val getBooleanField: (JvmJniHandleId, JvmJniHandleId) -> Boolean,
    val setBooleanField: (JvmJniHandleId, JvmJniHandleId, Boolean) -> Unit,
    val getByteField: (JvmJniHandleId, JvmJniHandleId) -> Int,
    val setByteField: (JvmJniHandleId, JvmJniHandleId, Int) -> Unit,
    val getCharField: (JvmJniHandleId, JvmJniHandleId) -> Int,
    val setCharField: (JvmJniHandleId, JvmJniHandleId, Int) -> Unit,
    val getShortField: (JvmJniHandleId, JvmJniHandleId) -> Int,
    val setShortField: (JvmJniHandleId, JvmJniHandleId, Int) -> Unit,
    val getStaticIntField: (JvmJniHandleId, JvmJniHandleId) -> Int,
    val setStaticIntField: (JvmJniHandleId, JvmJniHandleId, Int) -> Unit,
    val getStaticLongField: (JvmJniHandleId, JvmJniHandleId) -> Long,
    val setStaticLongField: (JvmJniHandleId, JvmJniHandleId, Long) -> Unit,
    val getStaticFloatField: (JvmJniHandleId, JvmJniHandleId) -> Float,
    val setStaticFloatField: (JvmJniHandleId, JvmJniHandleId, Float) -> Unit,
    val getStaticDoubleField: (JvmJniHandleId, JvmJniHandleId) -> Double,
    val setStaticDoubleField: (JvmJniHandleId, JvmJniHandleId, Double) -> Unit,
    val getStaticObjectField: (JvmJniHandleId, JvmJniHandleId) -> JvmJniHandleId?,
    val setStaticObjectField: (JvmJniHandleId, JvmJniHandleId, JvmJniHandleId?) -> Unit,
    val getStaticBooleanField: (JvmJniHandleId, JvmJniHandleId) -> Boolean,
    val setStaticBooleanField: (JvmJniHandleId, JvmJniHandleId, Boolean) -> Unit,
    val getStaticByteField: (JvmJniHandleId, JvmJniHandleId) -> Int,
    val setStaticByteField: (JvmJniHandleId, JvmJniHandleId, Int) -> Unit,
    val getStaticCharField: (JvmJniHandleId, JvmJniHandleId) -> Int,
    val setStaticCharField: (JvmJniHandleId, JvmJniHandleId, Int) -> Unit,
    val getStaticShortField: (JvmJniHandleId, JvmJniHandleId) -> Int,
    val setStaticShortField: (JvmJniHandleId, JvmJniHandleId, Int) -> Unit,
    val callVoidMethod: (JvmJniHandleId, JvmJniHandleId, List<JvmValue>) -> Unit,
    val callObjectMethod: (JvmJniHandleId, JvmJniHandleId, List<JvmValue>) -> JvmJniHandleId?,
    val callBooleanMethod: (JvmJniHandleId, JvmJniHandleId, List<JvmValue>) -> Boolean,
    val callByteMethod: (JvmJniHandleId, JvmJniHandleId, List<JvmValue>) -> Int,
    val callCharMethod: (JvmJniHandleId, JvmJniHandleId, List<JvmValue>) -> Int,
    val callShortMethod: (JvmJniHandleId, JvmJniHandleId, List<JvmValue>) -> Int,
    val callIntMethod: (JvmJniHandleId, JvmJniHandleId, List<JvmValue>) -> Int,
    val callLongMethod: (JvmJniHandleId, JvmJniHandleId, List<JvmValue>) -> Long,
    val throwObject: (JvmJniHandleId) -> Int,
    val throwNew: (JvmJniHandleId, String?) -> Int,
    val exceptionOccurred: () -> JvmJniHandleId?,
    val exceptionCheck: () -> Boolean,
    val exceptionClear: () -> Unit,
    val exceptionDescribe: () -> Unit,
    val fatalError: (String?) -> Nothing,
    val newString: (CharArray, Int) -> JvmJniHandleId,
    val newStringUtf: (String) -> JvmJniHandleId,
    val getStringLength: (JvmJniHandleId) -> Int,
    val getStringChars: (JvmJniHandleId) -> CharArray,
    val releaseStringChars: (JvmJniHandleId, CharArray) -> Unit,
    val getStringUtfLength: (JvmJniHandleId) -> Int,
    val getStringUtfChars: (JvmJniHandleId) -> ByteArray,
    val releaseStringUtfChars: (JvmJniHandleId, ByteArray) -> Unit,
    val monitorEnter: (JvmJniHandleId) -> Int,
    val monitorExit: (JvmJniHandleId) -> Int,
    val getArrayLength: (JvmJniHandleId) -> Int,
    val newBooleanArray: (Int) -> JvmJniHandleId,
    val newByteArray: (Int) -> JvmJniHandleId,
    val newCharArray: (Int) -> JvmJniHandleId,
    val newShortArray: (Int) -> JvmJniHandleId,
    val newIntArray: (Int) -> JvmJniHandleId,
    val newLongArray: (Int) -> JvmJniHandleId,
    val newFloatArray: (Int) -> JvmJniHandleId,
    val newDoubleArray: (Int) -> JvmJniHandleId,
    val getBooleanArrayElements: (JvmJniHandleId) -> BooleanArray,
    val releaseBooleanArrayElements: (JvmJniHandleId, BooleanArray, JvmJniArrayReleaseMode) -> Unit,
    val getBooleanArrayRegion: (JvmJniHandleId, Int, Int) -> BooleanArray,
    val setBooleanArrayRegion: (JvmJniHandleId, Int, BooleanArray) -> Unit,
    val getByteArrayElements: (JvmJniHandleId) -> ByteArray,
    val releaseByteArrayElements: (JvmJniHandleId, ByteArray, JvmJniArrayReleaseMode) -> Unit,
    val getByteArrayRegion: (JvmJniHandleId, Int, Int) -> ByteArray,
    val setByteArrayRegion: (JvmJniHandleId, Int, ByteArray) -> Unit,
    val getCharArrayElements: (JvmJniHandleId) -> CharArray,
    val releaseCharArrayElements: (JvmJniHandleId, CharArray, JvmJniArrayReleaseMode) -> Unit,
    val getCharArrayRegion: (JvmJniHandleId, Int, Int) -> CharArray,
    val setCharArrayRegion: (JvmJniHandleId, Int, CharArray) -> Unit,
    val getShortArrayElements: (JvmJniHandleId) -> ShortArray,
    val releaseShortArrayElements: (JvmJniHandleId, ShortArray, JvmJniArrayReleaseMode) -> Unit,
    val getShortArrayRegion: (JvmJniHandleId, Int, Int) -> ShortArray,
    val setShortArrayRegion: (JvmJniHandleId, Int, ShortArray) -> Unit,
    val getIntArrayElements: (JvmJniHandleId) -> IntArray,
    val releaseIntArrayElements: (JvmJniHandleId, IntArray, JvmJniArrayReleaseMode) -> Unit,
    val getIntArrayRegion: (JvmJniHandleId, Int, Int) -> IntArray,
    val setIntArrayRegion: (JvmJniHandleId, Int, IntArray) -> Unit,
    val getLongArrayElements: (JvmJniHandleId) -> LongArray,
    val releaseLongArrayElements: (JvmJniHandleId, LongArray, JvmJniArrayReleaseMode) -> Unit,
    val getLongArrayRegion: (JvmJniHandleId, Int, Int) -> LongArray,
    val setLongArrayRegion: (JvmJniHandleId, Int, LongArray) -> Unit,
    val getFloatArrayElements: (JvmJniHandleId) -> FloatArray,
    val releaseFloatArrayElements: (JvmJniHandleId, FloatArray, JvmJniArrayReleaseMode) -> Unit,
    val getFloatArrayRegion: (JvmJniHandleId, Int, Int) -> FloatArray,
    val setFloatArrayRegion: (JvmJniHandleId, Int, FloatArray) -> Unit,
    val getDoubleArrayElements: (JvmJniHandleId) -> DoubleArray,
    val releaseDoubleArrayElements: (JvmJniHandleId, DoubleArray, JvmJniArrayReleaseMode) -> Unit,
    val getDoubleArrayRegion: (JvmJniHandleId, Int, Int) -> DoubleArray,
    val setDoubleArrayRegion: (JvmJniHandleId, Int, DoubleArray) -> Unit,
    val newObjectArray: (Int, JvmJniHandleId, JvmJniHandleId?) -> JvmJniHandleId,
    val getObjectArrayElement: (JvmJniHandleId, Int) -> JvmJniHandleId?,
    val setObjectArrayElement: (JvmJniHandleId, Int, JvmJniHandleId?) -> Unit,
    val getObjectArrayRegion: (JvmJniHandleId, Int, Int) -> List<JvmJniHandleId?>,
    val setObjectArrayRegion: (JvmJniHandleId, Int, List<JvmJniHandleId?>) -> Unit,
) {
    companion object {
        fun bind(environment: JvmSimulatedJniEnvironment): JvmSimulatedJniFunctionTable =
            JvmSimulatedJniFunctionTable(
                newLocalRef = environment::newLocalRef,
                deleteLocalRef = environment::deleteLocalRef,
                newGlobalRef = environment::newGlobalRef,
                deleteGlobalRef = environment::deleteGlobalRef,
                newWeakGlobalRef = environment::newWeakGlobalRef,
                deleteWeakGlobalRef = environment::deleteWeakGlobalRef,
                getObjectRefType = environment::getObjectRefType,
                isSameObject = environment::isSameObject,
                ensureLocalCapacity = environment::ensureLocalCapacity,
                pushLocalFrame = environment::pushLocalFrame,
                popLocalFrame = environment::popLocalFrame,
                findClass = environment::findClass,
                getObjectClass = environment::getObjectClass,
                isInstanceOf = environment::isInstanceOf,
                getMethodId = environment::getMethodId,
                getStaticMethodId = environment::getStaticMethodId,
                getFieldId = environment::getFieldId,
                getStaticFieldId = environment::getStaticFieldId,
                getIntField = environment::getIntField,
                setIntField = environment::setIntField,
                getLongField = environment::getLongField,
                setLongField = environment::setLongField,
                getFloatField = environment::getFloatField,
                setFloatField = environment::setFloatField,
                getDoubleField = environment::getDoubleField,
                setDoubleField = environment::setDoubleField,
                getObjectField = environment::getObjectField,
                setObjectField = environment::setObjectField,
                getBooleanField = environment::getBooleanField,
                setBooleanField = environment::setBooleanField,
                getByteField = environment::getByteField,
                setByteField = environment::setByteField,
                getCharField = environment::getCharField,
                setCharField = environment::setCharField,
                getShortField = environment::getShortField,
                setShortField = environment::setShortField,
                getStaticIntField = environment::getStaticIntField,
                setStaticIntField = environment::setStaticIntField,
                getStaticLongField = environment::getStaticLongField,
                setStaticLongField = environment::setStaticLongField,
                getStaticFloatField = environment::getStaticFloatField,
                setStaticFloatField = environment::setStaticFloatField,
                getStaticDoubleField = environment::getStaticDoubleField,
                setStaticDoubleField = environment::setStaticDoubleField,
                getStaticObjectField = environment::getStaticObjectField,
                setStaticObjectField = environment::setStaticObjectField,
                getStaticBooleanField = environment::getStaticBooleanField,
                setStaticBooleanField = environment::setStaticBooleanField,
                getStaticByteField = environment::getStaticByteField,
                setStaticByteField = environment::setStaticByteField,
                getStaticCharField = environment::getStaticCharField,
                setStaticCharField = environment::setStaticCharField,
                getStaticShortField = environment::getStaticShortField,
                setStaticShortField = environment::setStaticShortField,
                callVoidMethod = environment::callVoidMethod,
                callObjectMethod = environment::callObjectMethod,
                callBooleanMethod = environment::callBooleanMethod,
                callByteMethod = environment::callByteMethod,
                callCharMethod = environment::callCharMethod,
                callShortMethod = environment::callShortMethod,
                callIntMethod = environment::callIntMethod,
                callLongMethod = environment::callLongMethod,
                throwObject = environment::throwObject,
                throwNew = environment::throwNew,
                exceptionOccurred = environment::exceptionOccurred,
                exceptionCheck = environment::exceptionCheck,
                exceptionClear = environment::exceptionClear,
                exceptionDescribe = environment::exceptionDescribe,
                fatalError = environment::fatalError,
                newString = environment::newString,
                newStringUtf = environment::newStringUtf,
                getStringLength = environment::getStringLength,
                getStringChars = environment::getStringChars,
                releaseStringChars = environment::releaseStringChars,
                getStringUtfLength = environment::getStringUtfLength,
                getStringUtfChars = environment::getStringUtfChars,
                releaseStringUtfChars = environment::releaseStringUtfChars,
                monitorEnter = environment::monitorEnter,
                monitorExit = environment::monitorExit,
                getArrayLength = environment::getArrayLength,
                newBooleanArray = environment::newBooleanArray,
                newByteArray = environment::newByteArray,
                newCharArray = environment::newCharArray,
                newShortArray = environment::newShortArray,
                newIntArray = environment::newIntArray,
                newLongArray = environment::newLongArray,
                newFloatArray = environment::newFloatArray,
                newDoubleArray = environment::newDoubleArray,
                getBooleanArrayElements = environment::getBooleanArrayElements,
                releaseBooleanArrayElements = environment::releaseBooleanArrayElements,
                getBooleanArrayRegion = environment::getBooleanArrayRegion,
                setBooleanArrayRegion = environment::setBooleanArrayRegion,
                getByteArrayElements = environment::getByteArrayElements,
                releaseByteArrayElements = environment::releaseByteArrayElements,
                getByteArrayRegion = environment::getByteArrayRegion,
                setByteArrayRegion = environment::setByteArrayRegion,
                getCharArrayElements = environment::getCharArrayElements,
                releaseCharArrayElements = environment::releaseCharArrayElements,
                getCharArrayRegion = environment::getCharArrayRegion,
                setCharArrayRegion = environment::setCharArrayRegion,
                getShortArrayElements = environment::getShortArrayElements,
                releaseShortArrayElements = environment::releaseShortArrayElements,
                getShortArrayRegion = environment::getShortArrayRegion,
                setShortArrayRegion = environment::setShortArrayRegion,
                getIntArrayElements = environment::getIntArrayElements,
                releaseIntArrayElements = environment::releaseIntArrayElements,
                getIntArrayRegion = environment::getIntArrayRegion,
                setIntArrayRegion = environment::setIntArrayRegion,
                getLongArrayElements = environment::getLongArrayElements,
                releaseLongArrayElements = environment::releaseLongArrayElements,
                getLongArrayRegion = environment::getLongArrayRegion,
                setLongArrayRegion = environment::setLongArrayRegion,
                getFloatArrayElements = environment::getFloatArrayElements,
                releaseFloatArrayElements = environment::releaseFloatArrayElements,
                getFloatArrayRegion = environment::getFloatArrayRegion,
                setFloatArrayRegion = environment::setFloatArrayRegion,
                getDoubleArrayElements = environment::getDoubleArrayElements,
                releaseDoubleArrayElements = environment::releaseDoubleArrayElements,
                getDoubleArrayRegion = environment::getDoubleArrayRegion,
                setDoubleArrayRegion = environment::setDoubleArrayRegion,
                newObjectArray = environment::newObjectArray,
                getObjectArrayElement = environment::getObjectArrayElement,
                setObjectArrayElement = environment::setObjectArrayElement,
                getObjectArrayRegion = environment::getObjectArrayRegion,
                setObjectArrayRegion = environment::setObjectArrayRegion,
            )
    }
}
