package me.moeyinlo.visualize.jvm.jni

class JvmSimulatedJniFunctionTable internal constructor(
    val newLocalRef: (JvmJniHandleId?) -> JvmJniHandleId?,
    val deleteLocalRef: (JvmJniHandleId?) -> Unit,
    val newGlobalRef: (JvmJniHandleId?) -> JvmJniHandleId?,
    val deleteGlobalRef: (JvmJniHandleId?) -> Unit,
    val newWeakGlobalRef: (JvmJniHandleId?) -> JvmJniHandleId?,
    val deleteWeakGlobalRef: (JvmJniHandleId?) -> Unit,
    val getObjectRefType: (JvmJniHandleId?) -> JvmJniReferenceType,
    val isSameObject: (JvmJniHandleId?, JvmJniHandleId?) -> Boolean,
    val ensureLocalCapacity: (Int) -> Int,
    val pushLocalFrame: (Int) -> Int,
    val popLocalFrame: (JvmJniHandleId?) -> JvmJniHandleId?,
    val findClass: (String) -> JvmJniHandleId,
    val getObjectClass: (JvmJniHandleId) -> JvmJniHandleId,
    val isInstanceOf: (JvmJniHandleId?, JvmJniHandleId) -> Boolean,
    val getMethodId: (JvmJniHandleId, String, String) -> JvmJniHandleId,
    val getStaticMethodId: (JvmJniHandleId, String, String) -> JvmJniHandleId,
    val getFieldId: (JvmJniHandleId, String, String) -> JvmJniHandleId,
    val getStaticFieldId: (JvmJniHandleId, String, String) -> JvmJniHandleId,
    val throwObject: (JvmJniHandleId) -> Int,
    val throwNew: (JvmJniHandleId, String?) -> Int,
    val exceptionOccurred: () -> JvmJniHandleId?,
    val exceptionCheck: () -> Boolean,
    val exceptionClear: () -> Unit,
    val exceptionDescribe: () -> Unit,
    val fatalError: (String?) -> Nothing,
    val newString: (CharArray, Int) -> JvmJniHandleId,
    val newStringUtf: (String) -> JvmJniHandleId,
    val getStringLength: (JvmJniHandleId) -> Int,
    val getStringChars: (JvmJniHandleId) -> CharArray,
    val releaseStringChars: (JvmJniHandleId, CharArray) -> Unit,
    val getStringUtfLength: (JvmJniHandleId) -> Int,
    val getStringUtfChars: (JvmJniHandleId) -> ByteArray,
    val releaseStringUtfChars: (JvmJniHandleId, ByteArray) -> Unit,
    val monitorEnter: (JvmJniHandleId) -> Int,
    val monitorExit: (JvmJniHandleId) -> Int,
    val getArrayLength: (JvmJniHandleId) -> Int,
    val newBooleanArray: (Int) -> JvmJniHandleId,
    val newByteArray: (Int) -> JvmJniHandleId,
    val newCharArray: (Int) -> JvmJniHandleId,
    val newShortArray: (Int) -> JvmJniHandleId,
    val newIntArray: (Int) -> JvmJniHandleId,
    val newLongArray: (Int) -> JvmJniHandleId,
    val newFloatArray: (Int) -> JvmJniHandleId,
    val newDoubleArray: (Int) -> JvmJniHandleId,
    val getBooleanArrayElements: (JvmJniHandleId) -> BooleanArray,
    val releaseBooleanArrayElements: (JvmJniHandleId, BooleanArray, JvmJniArrayReleaseMode) -> Unit,
    val getBooleanArrayRegion: (JvmJniHandleId, Int, Int) -> BooleanArray,
    val setBooleanArrayRegion: (JvmJniHandleId, Int, BooleanArray) -> Unit,
    val getByteArrayElements: (JvmJniHandleId) -> ByteArray,
    val releaseByteArrayElements: (JvmJniHandleId, ByteArray, JvmJniArrayReleaseMode) -> Unit,
    val getByteArrayRegion: (JvmJniHandleId, Int, Int) -> ByteArray,
    val setByteArrayRegion: (JvmJniHandleId, Int, ByteArray) -> Unit,
) {
    companion object {
        fun bind(environment: JvmSimulatedJniEnvironment): JvmSimulatedJniFunctionTable =
            JvmSimulatedJniFunctionTable(
                newLocalRef = environment::newLocalRef,
                deleteLocalRef = environment::deleteLocalRef,
                newGlobalRef = environment::newGlobalRef,
                deleteGlobalRef = environment::deleteGlobalRef,
                newWeakGlobalRef = environment::newWeakGlobalRef,
                deleteWeakGlobalRef = environment::deleteWeakGlobalRef,
                getObjectRefType = environment::getObjectRefType,
                isSameObject = environment::isSameObject,
                ensureLocalCapacity = environment::ensureLocalCapacity,
                pushLocalFrame = environment::pushLocalFrame,
                popLocalFrame = environment::popLocalFrame,
                findClass = environment::findClass,
                getObjectClass = environment::getObjectClass,
                isInstanceOf = environment::isInstanceOf,
                getMethodId = environment::getMethodId,
                getStaticMethodId = environment::getStaticMethodId,
                getFieldId = environment::getFieldId,
                getStaticFieldId = environment::getStaticFieldId,
                throwObject = environment::throwObject,
                throwNew = environment::throwNew,
                exceptionOccurred = environment::exceptionOccurred,
                exceptionCheck = environment::exceptionCheck,
                exceptionClear = environment::exceptionClear,
                exceptionDescribe = environment::exceptionDescribe,
                fatalError = environment::fatalError,
                newString = environment::newString,
                newStringUtf = environment::newStringUtf,
                getStringLength = environment::getStringLength,
                getStringChars = environment::getStringChars,
                releaseStringChars = environment::releaseStringChars,
                getStringUtfLength = environment::getStringUtfLength,
                getStringUtfChars = environment::getStringUtfChars,
                releaseStringUtfChars = environment::releaseStringUtfChars,
                monitorEnter = environment::monitorEnter,
                monitorExit = environment::monitorExit,
                getArrayLength = environment::getArrayLength,
                newBooleanArray = environment::newBooleanArray,
                newByteArray = environment::newByteArray,
                newCharArray = environment::newCharArray,
                newShortArray = environment::newShortArray,
                newIntArray = environment::newIntArray,
                newLongArray = environment::newLongArray,
                newFloatArray = environment::newFloatArray,
                newDoubleArray = environment::newDoubleArray,
                getBooleanArrayElements = environment::getBooleanArrayElements,
                releaseBooleanArrayElements = environment::releaseBooleanArrayElements,
                getBooleanArrayRegion = environment::getBooleanArrayRegion,
                setBooleanArrayRegion = environment::setBooleanArrayRegion,
                getByteArrayElements = environment::getByteArrayElements,
                releaseByteArrayElements = environment::releaseByteArrayElements,
                getByteArrayRegion = environment::getByteArrayRegion,
                setByteArrayRegion = environment::setByteArrayRegion,
            )
    }
}
